### ISSUE TITLE
改正了AndroidSDK版本以后，出现以下错误

### ISSUE THREAD

**Issue by longanwang** [linchaolong/ApkToolPlus#13]
把sdk版本改成24以后，之前的错误没有，会出现以下错误，类加载器没有发现类
但是我的ext的文件夹中包含了jfxrt.jar，在jdk的lib文件夹中也有ant-javafx.jar，所以不知道哪里出现了错误。希望各位同仁可以抽空指点一二。
![image](https://user-images.githubusercontent.com/29726540/28652786-77bf865c-72bc-11e7-8f5e-bdb62b529916.png)
Error:Internal error: (java.lang.ClassNotFoundException) com.android.prefs.AndroidLocation$AndroidLocationException
java.lang.ClassNotFoundException: com.android.prefs.AndroidLocation$AndroidLocationException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.jetbrains.jps.android.AndroidJpsUtil.getAndroidTarget(AndroidJpsUtil.java:404)
	at org.jetbrains.jps.android.AndroidJpsUtil.getAndroidPlatform(AndroidJpsUtil.java:480)
	at org.jetbrains.jps.android.builder.AndroidPreDexBuildTarget.computeRootDescriptors(AndroidPreDexBuildTarget.java:110)
	at org.jetbrains.jps.builders.impl.BuildRootIndexImpl.addRoots(BuildRootIndexImpl.java:72)
	at org.jetbrains.jps.builders.impl.BuildRootIndexImpl.<init>(BuildRootIndexImpl.java:62)
	at org.jetbrains.jps.cmdline.BuildRunner.load(BuildRunner.java:84)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:267)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:125)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:236)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler$$Lambda$4/2081584087.run(Unknown Source)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl.lambda$executeOnPooledThread$0(SharedThreadPoolImpl.java:42)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl$$Lambda$2/3213500.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

![image](https://user-images.githubusercontent.com/29726540/28652964-68c1c5d8-72bd-11e7-9cd0-d0ccd93f0218.png)

![image](https://user-images.githubusercontent.com/29726540/28661821-93b9fe72-72ea-11e7-87e8-61a608b8b7b9.png)
图中红色区域导入的包没有被使用。

**Comment by linchaolong** [comment]
@longanwang 解决了？看样子是jdk配置问题

**Comment by longanwang** [comment]
恩  刚开始没导入javafx的jar包，导入了之后就解决包没有引用的问题。
然后对于 classnotfondexception，吧.idea文件夹删除，重新运行一下项目就可以了。
谢了老哥，抽空帮我解答
