### ISSUE TITLE
Error:Android Pre Dex: [lib.JiaGu] Android SDK is not specified

### ISSUE THREAD

**Issue by dijiubuzhan** [linchaolong/ApkToolPlus#16]
when run com.linchaolong.apktoolplus.Main ,it occur "Error:Android Pre Dex: [lib.JiaGu] Android SDK is not specified" .how to slove it?

**Comment by dijiubuzhan** [comment]
configure the sdk and jdk

**Comment by dijiubuzhan** [comment]
Error:Internal error: (java.lang.NoSuchMethodError) com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
	at com.android.sdklib.BuildToolInfo.fromLocalPackage(BuildToolInfo.java:236)
	at com.android.sdklib.repository.AndroidSdkHandler.getLatestBuildTool(AndroidSdkHandler.java:772)
	at com.android.sdklib.repository.targets.PlatformTarget.<init>(PlatformTarget.java:144)
	at com.android.sdklib.repository.targets.AndroidTargetManager.getTargetMap(AndroidTargetManager.java:94)
	at com.android.sdklib.repository.targets.AndroidTargetManager.getTargets(AndroidTargetManager.java:80)
	at com.android.sdklib.repository.targets.AndroidTargetManager.getTargetFromHashString(AndroidTargetManager.java:154)
	at org.jetbrains.jps.android.AndroidJpsUtil.getAndroidTarget(AndroidJpsUtil.java:407)
	at org.jetbrains.jps.android.AndroidJpsUtil.getAndroidPlatform(AndroidJpsUtil.java:480)
	at org.jetbrains.jps.android.builder.AndroidPreDexBuildTarget.computeRootDescriptors(AndroidPreDexBuildTarget.java:110)
	at org.jetbrains.jps.builders.impl.BuildRootIndexImpl.addRoots(BuildRootIndexImpl.java:72)
	at org.jetbrains.jps.builders.impl.BuildRootIndexImpl.<init>(BuildRootIndexImpl.java:62)
	at org.jetbrains.jps.cmdline.BuildRunner.load(BuildRunner.java:84)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:267)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:125)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:236)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler$$Lambda$3/231980003.run(Unknown Source)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl.lambda$executeOnPooledThread$0(SharedThreadPoolImpl.java:42)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl$$Lambda$1/1555690610.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
